# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {
#         "text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
#         "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
#      "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = [
    {"category": "Celebrities", "type": "boolean", "difficulty": "medium",
  "question": "Michael Jackson had a pet python named &lsquo;Crusher&rsquo;.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Musicals & Theatres", "type": "boolean",
      "difficulty": "easy",
      "question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy in loving his mother.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
      "question": "Unturned originally started as a Roblox game.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
      "question": "Rabbits are rodents.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
      "question": "The weapon Clint Eastwood uses in &quot;Dirty Harry&quot; was a .44 Automag.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
      "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
      "question": "Musical artist, Future, collaborated with Kendrick Lamar for the song: &quot;Mask Off&quot;.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
      "question": "The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "Sound can travel through a vacuum.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
    "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
    "correct_answer": "True", "incorrect_answers": ["False"]}
]

# questions from https://opentdb.com/